// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ControllerInput
    {
        [DataMember(Name = "Position")]
        public DbVector3 Position;
        [DataMember(Name = "Rotation")]
        public DbQuaternion Rotation;
        [DataMember(Name = "IsAXPressed")]
        public bool IsAxPressed;
        [DataMember(Name = "WasAXPressedThisFrame")]
        public bool WasAxPressedThisFrame;
        [DataMember(Name = "IsBYPressed")]
        public bool IsByPressed;
        [DataMember(Name = "WasBYPressedThisFrame")]
        public bool WasByPressedThisFrame;
        [DataMember(Name = "IndexTriggerValue")]
        public float IndexTriggerValue;
        [DataMember(Name = "IndexTriggerPressedThisFrame")]
        public bool IndexTriggerPressedThisFrame;
        [DataMember(Name = "GripTriggerValue")]
        public float GripTriggerValue;
        [DataMember(Name = "GripTriggerPressedThisFrame")]
        public bool GripTriggerPressedThisFrame;
        [DataMember(Name = "JoystickPosition")]
        public DbVector2 JoystickPosition;

        public ControllerInput(
            DbVector3 Position,
            DbQuaternion Rotation,
            bool IsAxPressed,
            bool WasAxPressedThisFrame,
            bool IsByPressed,
            bool WasByPressedThisFrame,
            float IndexTriggerValue,
            bool IndexTriggerPressedThisFrame,
            float GripTriggerValue,
            bool GripTriggerPressedThisFrame,
            DbVector2 JoystickPosition
        )
        {
            this.Position = Position;
            this.Rotation = Rotation;
            this.IsAxPressed = IsAxPressed;
            this.WasAxPressedThisFrame = WasAxPressedThisFrame;
            this.IsByPressed = IsByPressed;
            this.WasByPressedThisFrame = WasByPressedThisFrame;
            this.IndexTriggerValue = IndexTriggerValue;
            this.IndexTriggerPressedThisFrame = IndexTriggerPressedThisFrame;
            this.GripTriggerValue = GripTriggerValue;
            this.GripTriggerPressedThisFrame = GripTriggerPressedThisFrame;
            this.JoystickPosition = JoystickPosition;
        }

        public ControllerInput()
        {
            this.Position = new();
            this.Rotation = new();
            this.JoystickPosition = new();
        }
    }
}
