// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ControllerInput
    {
        [DataMember(Name = "position")]
        public DbVector3 Position;
        [DataMember(Name = "rotation")]
        public DbQuaternion Rotation;
        [DataMember(Name = "joystick_position")]
        public DbVector2 JoystickPosition;
        [DataMember(Name = "is_ax_pressed")]
        public bool IsAxPressed;
        [DataMember(Name = "was_ax_pressed_this_frame")]
        public bool WasAxPressedThisFrame;
        [DataMember(Name = "is_by_pressed")]
        public bool IsByPressed;
        [DataMember(Name = "was_by_pressed_this_frame")]
        public bool WasByPressedThisFrame;
        [DataMember(Name = "index_trigger_value")]
        public float IndexTriggerValue;
        [DataMember(Name = "index_trigger_pressed_this_frame")]
        public bool IndexTriggerPressedThisFrame;
        [DataMember(Name = "grip_trigger_value")]
        public float GripTriggerValue;
        [DataMember(Name = "grip_trigger_pressed_this_frame")]
        public bool GripTriggerPressedThisFrame;

        public ControllerInput(
            DbVector3 Position,
            DbQuaternion Rotation,
            DbVector2 JoystickPosition,
            bool IsAxPressed,
            bool WasAxPressedThisFrame,
            bool IsByPressed,
            bool WasByPressedThisFrame,
            float IndexTriggerValue,
            bool IndexTriggerPressedThisFrame,
            float GripTriggerValue,
            bool GripTriggerPressedThisFrame
        )
        {
            this.Position = Position;
            this.Rotation = Rotation;
            this.JoystickPosition = JoystickPosition;
            this.IsAxPressed = IsAxPressed;
            this.WasAxPressedThisFrame = WasAxPressedThisFrame;
            this.IsByPressed = IsByPressed;
            this.WasByPressedThisFrame = WasByPressedThisFrame;
            this.IndexTriggerValue = IndexTriggerValue;
            this.IndexTriggerPressedThisFrame = IndexTriggerPressedThisFrame;
            this.GripTriggerValue = GripTriggerValue;
            this.GripTriggerPressedThisFrame = GripTriggerPressedThisFrame;
        }

        public ControllerInput()
        {
            this.Position = new();
            this.Rotation = new();
            this.JoystickPosition = new();
        }
    }
}
