// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class FunctionReadyCounter
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "player")]
        public SpacetimeDB.Identity Player;
        [DataMember(Name = "function")]
        public FunctionsCounter Function;
        [DataMember(Name = "counter")]
        public ulong Counter;

        public FunctionReadyCounter(
            ulong Id,
            SpacetimeDB.Identity Player,
            FunctionsCounter Function,
            ulong Counter
        )
        {
            this.Id = Id;
            this.Player = Player;
            this.Function = Function;
            this.Counter = Counter;
        }

        public FunctionReadyCounter()
        {
        }
    }
}
