// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class RaycastDebugger
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "tracker_type_attached")]
        public TrackerType TrackerTypeAttached;
        [DataMember(Name = "position")]
        public DbVector3 Position;

        public RaycastDebugger(
            ulong Id,
            SpacetimeDB.Identity Identity,
            TrackerType TrackerTypeAttached,
            DbVector3 Position
        )
        {
            this.Id = Id;
            this.Identity = Identity;
            this.TrackerTypeAttached = TrackerTypeAttached;
            this.Position = Position;
        }

        public RaycastDebugger()
        {
            this.Position = new();
        }
    }
}
