// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Tracker
    {
        [DataMember(Name = "TrackerId")]
        public uint TrackerId;
        [DataMember(Name = "TrackerType")]
        public TrackerType TrackerType;
        [DataMember(Name = "PlayerIdentity")]
        public SpacetimeDB.Identity PlayerIdentity;
        [DataMember(Name = "Position")]
        public DbVector3 Position;
        [DataMember(Name = "Rotation")]
        public DbQuaternion Rotation;

        public Tracker(
            uint TrackerId,
            TrackerType TrackerType,
            SpacetimeDB.Identity PlayerIdentity,
            DbVector3 Position,
            DbQuaternion Rotation
        )
        {
            this.TrackerId = TrackerId;
            this.TrackerType = TrackerType;
            this.PlayerIdentity = PlayerIdentity;
            this.Position = Position;
            this.Rotation = Rotation;
        }

        public Tracker()
        {
            this.Position = new();
            this.Rotation = new();
        }
    }
}
