// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Tracker
    {
        [DataMember(Name = "tracker_id")]
        public ulong TrackerId;
        [DataMember(Name = "tracker_type")]
        public TrackerType TrackerType;
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "position")]
        public DbVector3 Position;
        [DataMember(Name = "rotation")]
        public DbQuaternion Rotation;

        public Tracker(
            ulong TrackerId,
            TrackerType TrackerType,
            SpacetimeDB.Identity Identity,
            DbVector3 Position,
            DbQuaternion Rotation
        )
        {
            this.TrackerId = TrackerId;
            this.TrackerType = TrackerType;
            this.Identity = Identity;
            this.Position = Position;
            this.Rotation = Rotation;
        }

        public Tracker()
        {
            this.Position = new();
            this.Rotation = new();
        }
    }
}
