// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class VoxelWorld
    {
        [DataMember(Name = "world_id")]
        public ulong WorldId;
        [DataMember(Name = "chunk_size")]
        public ulong ChunkSize;
        [DataMember(Name = "voxel_size")]
        public float VoxelSize;

        public VoxelWorld(
            ulong WorldId,
            ulong ChunkSize,
            float VoxelSize
        )
        {
            this.WorldId = WorldId;
            this.ChunkSize = ChunkSize;
            this.VoxelSize = VoxelSize;
        }

        public VoxelWorld()
        {
        }
    }
}
