// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class VoxelGrid
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "x")]
        public long X;
        [DataMember(Name = "y")]
        public long Y;
        [DataMember(Name = "z")]
        public long Z;
        [DataMember(Name = "chunk_data")]
        public System.Collections.Generic.List<System.Collections.Generic.List<System.Collections.Generic.List<uint>>> ChunkData;

        public VoxelGrid(
            ulong Id,
            long X,
            long Y,
            long Z,
            System.Collections.Generic.List<System.Collections.Generic.List<System.Collections.Generic.List<uint>>> ChunkData
        )
        {
            this.Id = Id;
            this.X = X;
            this.Y = Y;
            this.Z = Z;
            this.ChunkData = ChunkData;
        }

        public VoxelGrid()
        {
            this.ChunkData = new();
        }
    }
}
