// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class VoxelWorld
    {
        [DataMember(Name = "world_id")]
        public ulong WorldId;
        [DataMember(Name = "voxel_size")]
        public float VoxelSize;

        public VoxelWorld(
            ulong WorldId,
            float VoxelSize
        )
        {
            this.WorldId = WorldId;
            this.VoxelSize = VoxelSize;
        }

        public VoxelWorld()
        {
        }
    }
}
