// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SendPointsToServerHandler(ReducerEventContext ctx, DbVector3 origin, System.Collections.Generic.List<DbVector3> points);
        public event SendPointsToServerHandler? OnSendPointsToServer;

        public void SendPointsToServer(DbVector3 origin, System.Collections.Generic.List<DbVector3> points)
        {
            conn.InternalCallReducer(new Reducer.SendPointsToServer(origin, points), this.SetCallReducerFlags.SendPointsToServerFlags);
        }

        public bool InvokeSendPointsToServer(ReducerEventContext ctx, Reducer.SendPointsToServer args)
        {
            if (OnSendPointsToServer == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSendPointsToServer(
                ctx,
                args.Origin,
                args.Points
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SendPointsToServer : Reducer, IReducerArgs
        {
            [DataMember(Name = "origin")]
            public DbVector3 Origin;
            [DataMember(Name = "points")]
            public System.Collections.Generic.List<DbVector3> Points;

            public SendPointsToServer(
                DbVector3 Origin,
                System.Collections.Generic.List<DbVector3> Points
            )
            {
                this.Origin = Origin;
                this.Points = Points;
            }

            public SendPointsToServer()
            {
                this.Origin = new();
                this.Points = new();
            }

            string IReducerArgs.ReducerName => "send_points_to_server";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SendPointsToServerFlags;
        public void SendPointsToServer(CallReducerFlags flags) => SendPointsToServerFlags = flags;
    }
}
