// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class FunctionReadyCounterHandle : RemoteTableHandle<EventContext, FunctionReadyCounter>
        {
            protected override string RemoteTableName => "function_ready_counter";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(FunctionReadyCounter row) => row.Id;

                public IdUniqueIndex(FunctionReadyCounterHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class IdxPositionFunctionIndex : BTreeIndexBase<(SpacetimeDB.Identity Player, FunctionsCounter Function)>
            {
                protected override (SpacetimeDB.Identity Player, FunctionsCounter Function) GetKey(FunctionReadyCounter row) => (row.Player, row.Function);

                public IdxPositionFunctionIndex(FunctionReadyCounterHandle table) : base(table) { }
            }

            public readonly IdxPositionFunctionIndex IdxPositionFunction;

            public sealed class IdxPlayerIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(FunctionReadyCounter row) => row.Player;

                public IdxPlayerIndex(FunctionReadyCounterHandle table) : base(table) { }
            }

            public readonly IdxPlayerIndex IdxPlayer;

            internal FunctionReadyCounterHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                IdxPositionFunction = new(this);
                IdxPlayer = new(this);
            }

            protected override object GetPrimaryKey(FunctionReadyCounter row) => row.Id;
        }

        public readonly FunctionReadyCounterHandle FunctionReadyCounter;
    }
}
