// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class RaycastDebuggerHandle : RemoteTableHandle<EventContext, RaycastDebugger>
        {
            protected override string RemoteTableName => "RaycastDebugger";

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(RaycastDebugger row) => row.Id;

                public IdUniqueIndex(RaycastDebuggerHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class PlayerIdentityIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(RaycastDebugger row) => row.PlayerIdentity;

                public PlayerIdentityIndex(RaycastDebuggerHandle table) : base(table) { }
            }

            public readonly PlayerIdentityIndex PlayerIdentity;

            internal RaycastDebuggerHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                PlayerIdentity = new(this);
            }

            protected override object GetPrimaryKey(RaycastDebugger row) => row.Id;
        }

        public readonly RaycastDebuggerHandle RaycastDebugger;
    }
}
