// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class RaycastDebuggerHandle : RemoteTableHandle<EventContext, RaycastDebugger>
        {
            protected override string RemoteTableName => "raycast_debugger";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(RaycastDebugger row) => row.Id;

                public IdUniqueIndex(RaycastDebuggerHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class IdxPlayerIdentityIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(RaycastDebugger row) => row.Identity;

                public IdxPlayerIdentityIndex(RaycastDebuggerHandle table) : base(table) { }
            }

            public readonly IdxPlayerIdentityIndex IdxPlayerIdentity;

            internal RaycastDebuggerHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                IdxPlayerIdentity = new(this);
            }

            protected override object GetPrimaryKey(RaycastDebugger row) => row.Id;
        }

        public readonly RaycastDebuggerHandle RaycastDebugger;
    }
}
