// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class TrackerHandle : RemoteTableHandle<EventContext, Tracker>
        {
            protected override string RemoteTableName => "tracker";

            public sealed class IdxPlayerIdentityIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(Tracker row) => row.Identity;

                public IdxPlayerIdentityIndex(TrackerHandle table) : base(table) { }
            }

            public readonly IdxPlayerIdentityIndex IdxPlayerIdentity;

            public sealed class TrackerIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Tracker row) => row.TrackerId;

                public TrackerIdUniqueIndex(TrackerHandle table) : base(table) { }
            }

            public readonly TrackerIdUniqueIndex TrackerId;

            internal TrackerHandle(DbConnection conn) : base(conn)
            {
                IdxPlayerIdentity = new(this);
                TrackerId = new(this);
            }

            protected override object GetPrimaryKey(Tracker row) => row.TrackerId;
        }

        public readonly TrackerHandle Tracker;
    }
}
