// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class TrackerHandle : RemoteTableHandle<EventContext, Tracker>
        {
            protected override string RemoteTableName => "Tracker";

            public sealed class PlayerIdentityIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(Tracker row) => row.PlayerIdentity;

                public PlayerIdentityIndex(TrackerHandle table) : base(table) { }
            }

            public readonly PlayerIdentityIndex PlayerIdentity;

            public sealed class TrackerIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(Tracker row) => row.TrackerId;

                public TrackerIdUniqueIndex(TrackerHandle table) : base(table) { }
            }

            public readonly TrackerIdUniqueIndex TrackerId;

            internal TrackerHandle(DbConnection conn) : base(conn)
            {
                PlayerIdentity = new(this);
                TrackerId = new(this);
            }

            protected override object GetPrimaryKey(Tracker row) => row.TrackerId;
        }

        public readonly TrackerHandle Tracker;
    }
}
