// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class VoxelWorldHandle : RemoteTableHandle<EventContext, VoxelWorld>
        {
            protected override string RemoteTableName => "VoxelWorld";

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(VoxelWorld row) => row.Id;

                public IdUniqueIndex(VoxelWorldHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal VoxelWorldHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(VoxelWorld row) => row.Id;
        }

        public readonly VoxelWorldHandle VoxelWorld;
    }
}
